server:
  port: ${PORT:8086}
  forward-headers-strategy: native

spring:
  mvc:
    redirect-context-relative: true
  application:
    name: toplms
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/toplms_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  host: "${server.host:localhost}"
  port: "${server.port:8086}"
  baseUrl: "${APP_BASE_URL:http://localhost:8086}"
  email: admin@gmail.com
  password: 123
  secretKey: "toplms_secure_super_secret_key_production_ready_2026"
demo:
  companyName: "demo academy"
  subdomain: demo # e.g. "demo" -> becomes demo.localhost
  planId: "GROWTH"
  name: admin
  adminEmail: demo@gmail.com
  adminPassword: 123